services:
  seq:
    image: datalust/seq:latest
    container_name: seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 5341:80
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379
